// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeuutceyxzciqppeajrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlldXV0Y2V5eHpjaXFwcGVhanJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyODA2MzEsImV4cCI6MjA1MTg1NjYzMX0.t_c8tr8PgDE5bxKbwbK4VmKhtberILwE0nW1Ec8wmqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);